version: '3.8'

services:
  # dev:
  #   container_name: ${CONTAINER_NAME}
  #   image: metaverse_server
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: sh -c "npm i && npm run start"
  #   ports:
  #     - '${LOCAL_PORT}:${CONTAINER_PORT}'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  db:
    image: postgres:11.5
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - '${DB_LOCAL_PORT}:${DB_CONTAINER_PORT}'
    volumes:
      - ./.postgres:/var/lib/postgresql/data2
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=auction@test.com
      - PGADMIN_DEFAULT_PASSWORD=rootroot
    ports:
      - "5050:80"

